# Generated by Django 5.0 on 2023-12-14 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enviado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO'), ('EXPIRADO', 'EXPIRADO')], default='ABIERTO', max_length=20)),
                ('type_doc', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO'), ('EXPIRADO', 'EXPIRADO')], default='MEMORANDO', max_length=20)),
                ('observacion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Observaciones')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('coddoc', models.CharField(max_length=50, verbose_name='Codigo')),
                ('docENV', models.FileField(blank=True, null=True, upload_to='empresa/doc')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Correspondencia Enviada',
                'verbose_name_plural': 'Correspondencias Enviadas',
                'db_table': 'sgd_env',
            },
        ),
    ]
