# Generated by Django 5.0 on 2023-12-14 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviado',
            name='docENV',
            field=models.FileField(blank=True, null=True, upload_to='doc/enviada'),
        ),
        migrations.AlterField(
            model_name='enviado',
            name='status',
            field=models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO'), ('EXPIRADO', 'EXPIRADO')], default='ABIERTO', max_length=20, verbose_name='Estado de la Doc.'),
        ),
        migrations.AlterField(
            model_name='enviado',
            name='type_doc',
            field=models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO'), ('EXPIRADO', 'EXPIRADO')], default='MEMORANDO', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.CreateModel(
            name='Recibido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO'), ('EXPIRADO', 'EXPIRADO')], default='ABIERTO', max_length=20, verbose_name='Estado de la Doc.')),
                ('type_doc', models.CharField(choices=[('ABIERTO', 'ABIERTO'), ('CERRADO', 'CERRADO'), ('EXPIRADO', 'EXPIRADO')], default='MEMORANDO', max_length=20, verbose_name='Tipo de Documento')),
                ('observacion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Observaciones')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('coddoc', models.CharField(max_length=50, verbose_name='Codigo')),
                ('docREC', models.FileField(blank=True, null=True, upload_to='doc/recibido')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Correspondencia Recibida',
                'verbose_name_plural': 'Correspondencias Recibids',
                'db_table': 'sgd_rec',
            },
        ),
    ]
