# Generated by Django 5.0 on 2023-12-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgd', '0003_alter_enviado_coddoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviado',
            name='type_doc',
            field=models.CharField(choices=[('CIRCULAR', 'CIRCULAR'), ('INFORME', 'INFORME'), ('OFICIO', 'OFICIO'), ('NOTA_DE_ENTREGA', 'NOTA DE ENTREGA'), ('NOTA_DE_SALIDA', 'NOTA DE SALIDA'), ('PUNTO_DE_CUENTA', 'PUNTO DE CUENTA')], default='MEMORANDO', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='recibido',
            name='type_doc',
            field=models.CharField(choices=[('CIRCULAR', 'CIRCULAR'), ('INFORME', 'INFORME'), ('OFICIO', 'OFICIO'), ('NOTA_DE_ENTREGA', 'NOTA DE ENTREGA'), ('NOTA_DE_SALIDA', 'NOTA DE SALIDA'), ('PUNTO_DE_CUENTA', 'PUNTO DE CUENTA')], default='MEMORANDO', max_length=20, verbose_name='Tipo de Documento'),
        ),
    ]
